# Generated by Django 5.0.3 on 2024-04-17 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_category_product_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
